config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  devise_for :users
  root 'static_pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog, only: %i[show edit update destroy]

  def new
    @blog = Blog.new
  end

  def edit; end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    respond_to do |format|
      if @blog.save
        format.html { redirect_to root_path, notice: I18n.t('notice.blogs_create.success') }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    if user_is_author(@blog, current_user)
      respond_to do |format|
        if @blog.update(blog_params)
          format.html { redirect_to root_path, notice: I18n.t('notice.blogs_update.success') }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, notice: I18n.t('notice.blogs_update.permission') }
      end
    end
  end

  def destroy
    if user_is_author(@blog, current_user)
      @blog.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: I18n.t('notice.blogs_destroy.success') }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, notice: I18n.t('notice.blogs_destroy.permission') }
      end
    end
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :description, :active)
  end

  def user_is_author(blog, user)
    blog.user_id == user.id
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    return unless current_user.present?

    blogs_query = Blog.where(active: true).or(Blog.where(user_id: current_user.id))
    @q = blogs_query.ransack(params[:q])
    @blogs = @q.result(distinct: true).order(id: :desc).paginate(page: params[:page], per_page: 5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def display_user_email(blog)
    user = User.find_by(id: blog.user_id)
    user.email if user
  end

  def current_user_is_author?(blog)
    blog.user_id == current_user.id
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.select :active, options_for_select([['Public', true], ['Private', false]], true) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Editing blog</h1>
      <%= render "form", blog: @blog %>
      <br>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>New blog</h1>
      <%= render "form", blog: @blog %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/"><%= I18n.t("views.home")%></a>
        </li>
        <% if current_user %>
          <li class="nav-item">
            <a class="nav-link" href="/blogs/new"><%= I18n.t("views.title_new")%></a>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= I18n.t("views.setting")%>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <% if current_user %>
              <li>
                <%= button_to "sign_out", destroy_user_session_path, method: :delete ,class: "btn btn-danger" %>
              </li>
            <% else %>
              <li>
                <%= button_to "sign_in", new_user_session_path, method: :get ,class: "btn btn-danger" %>
              </li>
              <li>
                <%= button_to "sign_up", new_user_registration_path, method: :get, class: "btn btn-danger"  %>
              </li>
            <% end %>
            </ul>
          </li>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HPGProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <div class="container-fluid">
      <div class="header">
        <%= render "layouts/navbar" %>
      </div>
      <div class="container-fluid">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_list_blog.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <table>
        <thead>
          <tr>
            <th>
              <%= sort_link(@q, :id, 'ID') %>
            </th>
            <th>
              <%= sort_link(@q, :title, 'Title') %>
            </th>
            <th>
              <%= sort_link(@q, :description, 'Description') %>
            </th>
            <th>
              <%= sort_link(@q, :active, 'Active') %>
            </th>
            <th>
              <span>
                <%= I18n.t("views.blog.poster")%>
              </span>
            </th>
            <th>
              <span>
                <%= I18n.t("views.blog.function")%>
              </span>
            </th>
            <th>
              <%= search_form_for @q, url: root_path, class: "d-flex" do |f| %>
                <%= f.search_field :title_cont, class: "form-control me-2", placeholder: "Search", aria: { label: "Search" } %>
                <%= f.submit "Search", class: "btn btn-outline-success", type: "submit" %>
              <% end %>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @blogs.each do |blog| %>
            <tr>
              <td><%= blog.id %></td>
              <td><%= blog.title %></td>
              <td><%= blog.description %></td>
              <td>
                  <% if blog.active %>
                    <i class="fa-solid fa-earth-americas"></i>
                  <% else %>
                    <i class="fa-solid fa-lock"></i>
                  <% end %>
              </td>
              <td><%= display_user_email(blog) %></td>
              <% if current_user_is_author?(blog) %>
                <td>
                  <ul>
                      <li>
                          <%= button_to edit_blog_path(blog), method: :get, class: "btn btn-primary" do %>
                            <i class="fas fa-edit"></i>
                          <% end %>
                      </li>
                      <li>
                        <%= button_to blog, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger", title: "Destroy" do %>
                          <i class="fas fa-trash-alt"></i>
                        <% end %>
                      </li>
                  </ul>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @blogs %>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<%= current_user.present? ? render("shared/list_blog") : content_tag(:p, "Please login to use the service !") %>